SYSTEM_CATALOGUE_FILE_NAME = "SystemCatalogue.txt"

FILE_HEADER_SIZE = 4
MAX_FILE_SIZE = 65540
PAGE_SIZE = 2048
MAX_PAGE_PER_FILE = 32

SYSTEM_CATALOGUE_PAGE_HEADER_SIZE = 8
SYSTEM_CATALOGUE_RECORD_SIZE = 116
SYSTEM_CATALOGUE_RECORD_NAME_SIZE = 10
SYSTEM_CATALOGUE_RECORD_HEADER_SIZE = 16
SYSTEM_CATALOGUE_MAX_RECORD_PER_PAGE = 17
SYSTEM_CATALOGUE_RECORD_FIELD_NAME_SIZE = 10

DATA_FILE_PAGE_HEADER_SIZE = 8
DATA_FILE_RECORD_HEADER_SIZE = 2
DATA_FILE_RECORD_SIZE = 42
DATA_FILE_MAX_RECORD_PER_PAGE = 48